### ISSUE TITLE
company-lsp no longer on melpa

### ISSUE THREAD

**Issue by saanvik** [daviderestivo/galactic-emacs#27]
New install, and I got hung up because it couldn't install company-lsp because it's no longer on melpa.

Also, it isn't supported in lsp-mode anymore - https://github.com/emacs-lsp/lsp-mode#overview

**Comment by daviderestivo** [comment]
@saanvik,  thanks for reporting it... I'm gonna fix it as soon as possible.

**Comment by daviderestivo** [comment]
Fixed in https://github.com/daviderestivo/galactic-emacs/pull/28
