### ISSUE TITLE
A few bumps for a beginner; probably my fault, but ...

### ISSUE THREAD

**Issue by saanvik** [daviderestivo/galactic-emacs#29]
Re-installed after the fix for company-lsp; still hitting a few issues.

On startup, I see, in the `*Warnings*`

`Error (use-package): erc/:config: Symbol’s value as variable is void: freenode-login-password Disable showing Disable logging
Error (use-package): atom-one-dark-theme/:init: Wrong number of arguments: (3 . 4), 2 Disable showing Disable logging
Error (use-package): smart-mode-line/:catch: Wrong number of arguments: (3 . 4), 2 Disable showing Disable logging`

The erc issue is a known one; I don't have a freenode account.  That error doesn't bother me.  

But the really annoying this is that C-x C-f won't work.  I get `Invalid function: treemacs-get-icon-value`; in `*Messages*` I see `helm-icons--treemacs-icon: Invalid function: treemacs-get-icon-value`

These are probably issues I've introduced, but I've been unable to progress on resolving them.  

Let me know if I can help by providing any more data.  

BTW, I know this is a terrible bug report, but I'm not really sure of how to resolve this without creating an issue.

**Comment by saanvik** [comment]
GNU Emacs 28.0.50
Mac OSX Big Sur

**Comment by saanvik** [comment]
I think I've found the issue.  Starting in 28.0.50, the the signature of function make-obsolete to make the third (when ) argument required, when it used to be optional.   This appears to be breaking a bunch of things.  See https://github.com/emacs-mirror/emacs/blob/f695fdfef7d8e9ea4e0e17b69e0a28f952db55d6/etc/NEWS#L2426

So, this is not a bug in your project, but an issue for packages that don't meet this requirement.   The solution is to install a previous version of emacs.

**Comment by daviderestivo** [comment]
@saanvik First of all thanks for using this home-made emacs packages distribution. I'm sorry but I did not see this issue before (I had two very intense days at work). I'ma happy to see you have already fixed all the issues :). Have fun.

P.S.: Please lemme know if you have some advices on what could be improved.

**Comment by saanvik** [comment]
Thanks, I really appreciate the creation you've made here.  Perhaps until this change in 28.0.50 shakes out, you might want to update your README to remove the version 28 instructions and note the issue with version 28.

**Comment by daviderestivo** [comment]
> Thanks, I really appreciate the creation you've made here. Perhaps until this change in 28.0.50 shakes out, you might want to update your README to remove the version 28 instructions and note the issue with version 28.

I have 

> Installing [all-the-icons](https://github.com/domtronn/all-the-icons.el) and changing helm-icons-provider to "all-the-icons" resolved the issue with C-x C-f

Can you show me what you have changes please?

**Comment by daviderestivo** [comment]
> Installing [all-the-icons](https://github.com/domtronn/all-the-icons.el) and changing helm-icons-provider to "all-the-icons" resolved the issue with C-x C-f

Fixed in https://github.com/daviderestivo/galactic-emacs/pull/30
