### ISSUE TITLE
Not installing correctly

### ISSUE THREAD

**Issue by m-c-g** [daviderestivo/galactic-emacs#7]
When I installed emacs 26 with brew the executable only worked when started from the terminal with the -nw option. Starting without it or from the icon in Applications crashed.

When installing emacs 27 this happens.

```
==> make
Last 15 lines from /Users/mark/Library/Logs/Homebrew/emacs-head/03.make:
Fatal error 4: Illegal instruction
make[3]: *** [../../lisp/cedet/semantic/bovine/c-by.el] Abort trap: 6
make[2]: *** [semantic] Error 2
make[2]: *** Waiting for unfinished jobs....
  ELC      ../lisp/button.elc
  INFO     Scraping files for cal-loaddefs.el...28%
  ELC      ../lisp/case-table.elc
  INFO     Scraping files for cal-loaddefs.el...57%
  INFO     Scraping files for cal-loaddefs.el...71%
  ELC      ../lisp/composite.elc
  INFO     Scraping files for cal-loaddefs.el...92%
  INFO     Scraping files for cal-loaddefs.el...done
make[1]: *** [../lisp/loaddefs.el] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [src] Error 2
```

**Comment by daviderestivo** [comment]
@m-c-g : Can you please provide more info on what you have done and on your environment?

**Comment by m-c-g** [comment]
My hardware is a bit outdated, an unsupported late 2009 mac mini upgraded to 8Gb, I'm running a patched version of Mojave, I've noticed no problems except minor color glitches in some interface components and after Mojave updates I sometimes have to re-patch it.  

I tried to install using brew according to your instructions.  It seems like the current xcode is maybe not getting along with emacs?  

I uninstalled your emacs 26 which was crashing with the gui and tried 27 which wouldn't compile. I can reinstall 26 and send you the dumps if that might help.

**Comment by m-c-g** [comment]
Here is what emacs 26 does, the dump files are what comes up if I try to reopen, crash.txt is from trying to start in the terminal, crash2.txt from the application icon.

![Screen Shot 2019-09-27 at 8 48 24 PM](https://user-images.githubusercontent.com/23322930/65811184-59727600-e169-11e9-81e0-d81018c6bdd1.png)
![Screen Shot 2019-09-27 at 8 49 35 PM](https://user-images.githubusercontent.com/23322930/65811186-5f685700-e169-11e9-98bd-878cb5d8eee4.png
[crash2.txt.gz](https://github.com/daviderestivo/galactic-emacs/files/3665075/crash2.txt.gz)
)
[crash.txt.gz](https://github.com/daviderestivo/galactic-emacs/files/3665070/crash.txt.gz)

**Comment by daviderestivo** [comment]
From the crash logs, in both cases (crash.txt.gz and chrash2.txt.gz), I can see `Exception Type:        EXC_BAD_INSTRUCTION (SIGABRT)`

that seems very strange. I assume you tried to install Emacs 26 using:

```
brew install emacs-head --with-cocoa --with-no-frame-refocus --with-imagemagick --with-multicolor-fonts
```

Can you try to download the already bottled version for Mojave and tell me if it still crash? you can do it simply:

```
brew install emacs-head
```

Which Xcode version are you using? Can you please provide the output of the below command?

```
/usr/bin/xcodebuild -version
```

**Comment by m-c-g** [comment]
It appears xcode wasn't installed correctly, I was getting this:

xcode-select: error: tool ‘xcodebuild’ requires Xcode, but active developer directory ‘/Library/Developer/CommandLineTools’ is a command line tools instance

After fixing this I get:

➜  ~ /usr/bin/xcodebuild -version
Xcode 10.3
Build version 10G8

but after 
brew install emacs-head
I'm still getting a crash with the gui.
[crash3.txt.gz](https://github.com/daviderestivo/galactic-emacs/files/3666084/crash3.txt.gz)

**Comment by daviderestivo** [comment]
I have the feeling it has to do with the Cairo library. Can you please do the following:

`brew uninstall --ignore-dependencies cairo  && brew install cairo`

Once done please try once again and provide me the output of the previous command.

**Comment by m-c-g** [comment]
I did 

brew uninstall --ignore-dependencies cairo && brew install cairo

[crash4.txt.gz](https://github.com/daviderestivo/galactic-emacs/files/3667376/crash4.txt.gz)
then ran the previously installed emacs, output is in crash4.
Did you want me to reinstall emacs after the cairo change or just test with what I had previously installed?
[crash4.txt.gz](https://github.com/daviderestivo/galactic-emacs/files/3667378/crash4.txt.gz)

**Comment by daviderestivo** [comment]
> Did you want me to reinstall emacs after the cairo change or just test with what I had previously installed?

Yes, and please provide me the output of `brew info cairo`.

**Comment by m-c-g** [comment]
~ brew info cairo
cairo: stable 1.16.0 (bottled), HEAD
Vector graphics library with cross-device output support
https://cairographics.org/
/usr/local/Cellar/cairo/1.16.0_2 (117 files, 5.5MB) *
  Poured from bottle on 2019-09-29 at 06:13:22
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/cairo.rb
==> Dependencies
Build: pkg-config ✔
Required: fontconfig ✔, freetype ✔, glib ✔, libpng ✔, lzo ✔, pixman ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 75,773 (30 days), 256,084 (90 days), 939,943 (365 days)
install_on_request: 6,574 (30 days), 22,649 (90 days), 82,848 (365 days)
build_error: 0 (30 days)

**Comment by m-c-g** [comment]
==> Summary
🍺  /usr/local/Cellar/emacs-head/26.3_1: 3,996 files, 123.0MB
➜  ~ rm /Applications/Emacs.app
rm: /Applications/Emacs.app: No such file or directory
➜  ~ ln -s /usr/local/opt/emacs-head/Emacs.app /Applications
➜  ~ emacs
Fatal error 4: Illegal instruction[1]    77344 abort      emacs
➜  ~
[crash5.txt.gz](https://github.com/daviderestivo/galactic-emacs/files/3668822/crash5.txt.gz)

**Comment by daviderestivo** [comment]
So Cairo is the same version as mine (I'm running on Mojave as well). What I can suggest is the following:

1. Reinstall cairo recompiling it from sources

`brew uninstall --ignore-dependencies cairo  && brew install --HEAD cairo`

2. Reinstall emacs 26.3 recompiling from sources

`brew install emacs-head --with-cocoa --with-no-frame-refocus --with-imagemagick --with-multicolor-fonts`

**Comment by m-c-g** [comment]
It seems like somethings going wrong in the brew install/build process (I just use brew, I'm haven't looked at how it works). So I tried looking at the output of brew doctor:
----------------
➜  ~ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/SUVMMFaker.dylib
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a
➜  ~
----------------
The unbrewed tk/tcl stuff apparently comes from the way R gets installed with brew, but what looks interesting is
SUVMMFaker.dylib
and other "fake" header files which seems to be part of the patching system that allows me to run Mojave on my old mini. http://dosdude1.com/mojave/

I'm thinking this could possibly be why I'm having the problem, otherwise I think you'd be getting other reports from users of newer macs.
If you don't think this is the case I'll try recompiling/installing cairo.

**Comment by daviderestivo** [comment]
> I'm thinking this could possibly be why I'm having the problem, otherwise I think you'd be getting other reports from users of newer macs.

To be honest, this is the first time I see such an issue and I'm not familiar with this patch that allow you to run Mojave on the old mini.

> If you don't think this is the case I'll try recompiling/installing cairo.

I would make a try anyway just to see if the problem is on Cairo or not :) ...

**Comment by daviderestivo** [comment]
@m-c-g: did you try to reinstall Cairo from HEAD and the recompile Emacs?

**Comment by daviderestivo** [comment]
Closing it, because of inactivity. @m-c-g feel free to re-open it in case it's needed.
