### ISSUE TITLE
Personal setup? 

### ISSUE THREAD

**Issue by joseph-vidal-rosset** [daviderestivo/galactic-emacs#8]
Hello, 

First, many thanks for sharing galactic-emacs. It is a very nice starter-kit, and the setup is very clear. Congratulations for this useful work. 

I have two questions: 
First, I do not succeed to identify the file where is the list of the packages that are downloaded and installed. 
Second, I would be pleased to write another file to download other useful packages and to load personal setup. I am waiting to your adices to do so, because I do not want to break the installation when I will upgrade it. 

Best wishes, 
Jo.

**Comment by daviderestivo** [comment]
Hi @joseph-vidal-rosset,

thanks for having found galactic-emacs very useful. I'm very glad to hear you plan to use it. 

Regarding your questions:
1. The list of the packages installed by default can be found [here](https://github.com/daviderestivo/galactic-emacs/blob/master/doc/included_packages.md)
2. Before you start emacs please edit ~/.emacs.d/personal.el.example adding your personal information and rename it to ~/.emacs.d/personal.el. You could add in here additional packages you wish to install.

Have fun and please lemme know if you encounter any problem.

Regards,
Davide

**Comment by joseph-vidal-rosset** [comment]
Thanks Davide for your reply. My question was not precise enough, sorry. I wondered about the code that I can use to download and install these packages in elpa. 
For example in Kitchin's scimax you can see this code: 

`(require 'package)
(setq package-archives
      '(("melpa" . "https://melpa.org/packages/")
        ("melpa-stable" . "https://stable.melpa.org/packages/")
        ("org" . "https://orgmode.org/elpa/")
        ("gnu" . "https://elpa.gnu.org/packages/")
        ))
(package-initialize)
(when (not package-archive-contents)
  (package-refresh-contents))
(defvar my-packages-package-list "List of custom packages to install.")
;;; this allows for dynamically update and install packages while
;;; Emacs is running, by modifying this list, and then evaluating it
(setq my-packages-package-list
      '( aggressive-indent
        all-the-icons
        all-the-icons-dired
        all-the-icons-gnus
        all-the-icons-ibuffer
        auctex
        auto-dictionary
        autoinsert
        autopair
        etc.
         )
       )
(mapc #'(lambda (package)
	  (unless (package-installed-p package)
	    (package-install package)))
      my-packages-package-list)`

But I have understood that the code in galactic-emacs is based on use-package. An example of minimal lines that I have to write to install any package would be helpful, if you have time to write it here. 
Again, many thanks for your useful work. 
Best wishes, 
Jo.

**Comment by daviderestivo** [comment]
Hi @joseph-vidal-rosset 

the `package` initialisation part is already included in `init.el`

```
(if (version< emacs-version "27")
    (package-initialize))
(require 'package)
(setq package-archives
      '(("melpa" . "https://melpa.org/packages/")
        ("melpa-stable" . "https://stable.melpa.org/packages/")
        ("org" . "https://orgmode.org/elpa/")
        ("gnu" . "https://elpa.gnu.org/packages/")))

;; Change the below priorities if you prefer melpa-stable packages.
;; Higher is better.
(setq package-archive-priorities
      '(("melpa" .  4)
        ("melpa-stable" . 3)
        ("org" . 2)
        ("gnu" . 1)))

;; Bootstrap `use-package'
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(eval-when-compile
  (require 'use-package))
(use-package use-package-ensure-system-package
  :ensure t)
```

So what you should do is simply add in personal.el the packages you want to install. Let's make an example:

```
(use-package aggressive-indent
  :ensure t
 :configure
 (global-aggressive-indent-mode 1))

(use-package autoinsert
  :ensure t
)

(use-package auctex
  :ensure t
)
```

I hope it's more clear now :). Please make a try and don't hesitate to contact me in case of issue/questions.

Regards,
Davide

**Comment by daviderestivo** [comment]
In addition I have added in `personal.el.example` an example of for the installation of an additional packages:

```

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Galactic Emacs additional packages ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; Please specify here the additional packages you might want to
;; install. One package per `use-package' declaration. See below
;; examples:

;;(use-package aggressive-indent
;; :ensure t
;; :config
;; (global-aggressive-indent-mode 1)
;; (add-to-list 'aggressive-indent-excluded-modes 'html-mode))
```

**Comment by joseph-vidal-rosset** [comment]
Many thanks  for your help,  Davide, I am going  to install my  setup of
galactic-emacs and I will keep you informed. 

 Best wishes,
-- 
Jo.

**Comment by daviderestivo** [comment]
Have fun. I keep this issue opened. You can close it once you feel confident your setup is working as you expect.

**Comment by joseph-vidal-rosset** [comment]
Again, thanks. Before closing this issue, I will write a report, hoping it
will be also useful for others.

Best wishes,
Jo.

**Comment by joseph-vidal-rosset** [comment]
Hello Davide. 
I wanted to get an .emacs.d/ from your galactic-emacs both adapted to my use of emacs (with my keybindings, my org-export settings, my agenda settings, etc.) and with the benefit of using of your updates. But, unfortunately, it is too much work and it is probably useless to try it, because I have to change many parts of your setup, as I already did for a first .emacs.d/  setup here: 
[https://github.com/joseph-vidal-rosset/stanemacs](url)
that is inspired from galactic-emacs but also different and lighter. 
The point is that personal.el in galactic emacs is _not_ a file that overrides the setup in ~/.emacs.d/conf/ . In this respect, the galactic user cannot really add his own setup without inspecting the files in ~/.emacs.d/conf and without changing some part of them, by contrast, with scimax setup [https://github.com/jkitchin/scimax](url) that contains a user directory where user.el allows a personal setup free of other tasks on scimax settings. 
I regret sincerely to give up at the moment my project (I cannot spend more time on emacs now), but I hope that this report will inspire you. 
Anyway and again, congratulations for galactic-emacs, because it is a nice starter-kit, even if it as at the moment not adaptive enough, IMHO. 
We stay in touch !
Best wishes, 
Jo.

**Comment by daviderestivo** [comment]
Hi @joseph-vidal-rosset,

thanks a lot for your valid input. I perfectly understand your points. I will work on galactic-emacs to make user customisations more easier in the future.

Thanks and regards,
Davide

**Comment by joseph-vidal-rosset** [comment]
Dear David,

You'll can count on me to test galactic-emacs as new user !

Best wishes !

Jo.

Le mer. 5 août 2020 à 13:29, Davide Restivo <notifications@github.com> a
écrit :
